### PR TITLE
Use new docker package/API, replace references to courseraprogramming

### LINKED ISSUE #16: Update to `docker` package
I'm upgrading the docker graders for my course and would love to use more of the architecture provided by Coursera. However, I currently cannot run any of the running/testing environment. 

It seems that the interaction with Docker is based around a package called `docker-py` (version `1.10.4`) which is incompatible with the current version of Docker on MacOS. Currently my grader has some `pytest` testing which uses the `docker` package (version `4.4.1`), which does seem to work.

I had a quick look and it looks like both packages point to the same repository, but that the former was discontinued and replaced by the latter. It would be great if you could upgrade the package to use this newer version so it is usable on more systems.

### PR DESCRIPTION
**Pull request by echuber2**
Fixes #16 

This attempts to use the new `docker` package instead of the old `docker-py`. Old references to `Client` are now `APIClient`. The exit code from some of the Docker API calls (`wait`) is now retrieved from a dictionary.

Also, I replaced references to `courseraprogramming` with `coursera_autograder` wherever I found them, and removed some `pyc` files cluttering the repo, adding `*.pyc` to a gitignore.

The grade test feature seems to work as usual after making these changes but I haven't tested it broadly. Also, I'm using Linux on x86-64, so I have no idea if this actually resolves the issues on ARM-based macOS.

### CODE REVIEW

**Comment by echuber2** [comment]
I think that not all of the references to `courseraprogramming` are still valid (after renaming to `coursera_autograder`). However, note that `courseraprogramming` relies on `docker-py` and its old API, so there's a conflict if `coursera_autograder` still must rely on `courseraprogramming` for anything.

**Comment by Dekker1** [comment]
Any news on the status of this PR? I'm waiting on this change to be able to convert my existing manual testing system to the `coursera_autograder` system.

**Comment by echuber2** [comment]
> Any news on the status of this PR? I'm waiting on this change to be able to convert my existing manual testing system to the `coursera_autograder` system.

Well, I'm not sure if this PR will ever be merged. (I don't work for Coursera, and it looks like some of their own commits since then have made similar/conflicting changes.) It might be simple to resolve the conflicts now but I don't have time to try it this week. If you want to use the PR branch as-is to try it out, you can clone it from the branch I forked temporarily (link to repo at the top of this GitHub page). But I can't make any guarantees about how well it works.

**Comment by echuber2** [comment]
I made another attempt at this PR at https://github.com/coursera/coursera_autograder/pull/41 so I'll close this one.

**Pull request closed without merging**
