### PR TITLE
documentation about filename and userId environment variables

### LINKED ISSUE #1: fileName or filename?
In the readme, the example shows passing a json object with property `fileName`, but other examples show `filename`. Which is correct?

### PR DESCRIPTION
**Pull request by echuber2**
It looks like `fileName` should be `filename`. (If it's vice-versa then the opposite PR needs to be made so the examples are consistent.)

Fixes #1

### CODE REVIEW

**Review by sashi-coursera — APPROVED** [review]
Thank you.

**Review by sashi-coursera — CHANGES_REQUESTED** [review]
Actually.. this variable can be confusing, so we removed it from the documentation.
this filename : refers to the actual filename (uploaded filename of the learner), which doesn't have much use, as we rename the learner's submission in our production system as suggested in the programming assignment.

**Comment by echuber2** [comment]
Thanks! If the only point of it is is to pass the `filename` environment variable through to the local grader, and this is the same as the suggested filename that production would expose as `filename`, then maybe it's still useful to have `filename` and `userId` for local simulation or CI. So, I've edited this PR to just a little bit of documentation for those optional environment variables.

**Comment by sashi-coursera** [comment]
filename is NOT the suggested file provided in edit programming assignment page. 

E.g. Lets say an author set the "index.py" as suggested file in programming assignment page. If a learner submits "random.py", coursera infrastructure renames "random.py" to "index.py"and then copies to /shared/submission folder for grading. We pass the learner's submitted filename ("random.py") as environment filename variable to the grader.  We will continue to pass this environment variable, although I am not sure how authors are using this information. 

Hope this clarifies. Happy to answer if there any follow up questions.

**Comment by echuber2** [comment]
Thanks for your reply. I've updated the PR to reflect my current understanding. Please let me know if what I've put is correct. (If you feel this isn't useful to publish on the official readme, you're free to simply close the PR instead of merging it.)

**Review by sashi-coursera — APPROVED** [review]
Looks great. Thank you.

**Pull request merged**
